### ISSUE TITLE
support for different storage classes

### ISSUE THREAD

**Issue by liornaimalon** [marko-bast/aws-s3-glacier-restore#3]
Hi,
while i was able to restore the files without issue, the status (-s) command fails to retrieve the correct status of the files because it seems it only considers 'GLACIER' storage class, while my files are in deep glacier, so the value is 'DEEP_ARCHIVE'
on the status it returns the following: 

> Object {path} storageClass is not Glacier
> Restored count: 0/1
> Also found: 1 files with storage class that is not Glacier. For them restore isn't needed

while the file is in fact in restoration process.

**Comment by rxvt** [comment]
I also had this issue and I've raised PR https://github.com/marko-bast/aws-s3-glacier-restore/pull/5 to address it.

Not sure if the author is still maintaining this tool, but if not my fork has this patch applied.

**Comment by marko-bast** [comment]
I'm still maintaining it. Thanks for the great PR. I've merged it and it should work now
